name: Dependabot Keep-Alive (org)

on:
  schedule:
    - cron: "0 0 1 */3 *"
  workflow_dispatch:
    inputs:
      mode:
        description: 'runner mode: hosted or selfhosted'
        required: false
        default: 'hosted'
        
# 👇 this is critical for org-wide operations
permissions:
  contents: read
  pull-requests: write
  issues: write
  # Note: For org-wide scanning, ensure ORG_READ_TOKEN secret has:
  # - repo (full control of private repositories)
  # - OR public_repo (access to public repositories only)

jobs:
  call:
    uses: ./.github/workflows/reusable.yml
    secrets: inherit
    with:
      runs-on: ${{ github.event_name == 'workflow_dispatch' && inputs.mode == 'selfhosted'
        && '["self-hosted","dependabot"]' || '["ubuntu-latest"]'  }}
      team-handle: "@sujithq-org/dependency-maintainers"
      scan-mode: 'org'  # Use organization mode to scan all repos with dependabot
      org: 'sujithq'    # Specify the organization to scan
